---
- name: Set up sufia development environment
  hosts: all 
  vars:
    app_name: "sufiaApp"
    ruby_version: "2.3.1"
    rails_version: "5.0.0.1"
    sufia_version: "7.2.0"
    hydra_role_management_version: "0.2.2"
    # curation_concerns gem 1.7 was causing problems as time of this writing
    curation_concerns_version: "1.6.3"
    figaro_version: "1.1.1"
    # flipflop gem has not been released so we are using a copy from github
    gemset: "sufia"
    sources: "source ~/.bashrc; source ~/.bash_profile; source ~/.profile;"
  tasks:
    - name: Update package list 
      become: yes
      apt_repository: 
        repo: "ppa:webupd8team/java" 
        state: present 
        update_cache: yes
    - name: Install required packages
      become: yes
      apt: name={{item}} state=present
      with_items:
        - curl
        - python-software-properties
        - nodejs
        - redis-server
        - unzip
    - name: Ensure redis-server is running
      become: yes
      service: name=redis-server state=started enabled=yes
    - name: Accept Oracle license
      shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
    - name: Install Java 8
      become: yes
      apt: name="oracle-java8-installer" state=present
    - name: Install RVM
      # CHECK
      shell: "{{sources}} curl -sSL https://get.rvm.io | bash"      
      args:
        warn: no
        creates: "~/.rvm"
    - name: Setup RVM
      # CHECK
      shell: "{{sources}} rvm install {{ruby_version}}; rvm use {{ruby_version}}@{{gemset}} --default --create"
      args:
        executable: /bin/bash
    - name: Install Rails gems
      # CHECK
      shell: "{{sources}} gem install bundler; gem install rails -v {{rails_version}}"
      args:
        executable: /bin/bash
    - name: Create application workspace directory
      become: yes
      file: 
        path: /var/workspace
        mode: 0777
        state: directory
    - name: Link workspace application directory
      shell: "{{sources}} ln -s /var/workspace ~/workspace"
      args:
        executable: /bin/bash
        creates: "~/workspace"
    # Start of clean application
    - name: Create Rails application
      # CHECK
      shell: "{{sources}} rails new ~/workspace/{{app_name}}"      
      args:
        executable: /bin/bash
        creates: "~/workspace/{{app_name}}"
    - name: Add Sufia 7 gem and requirements to Rails project
      # CHECK
      blockinfile:
        dest: ~/workspace/{{app_name}}/Gemfile
        # insertafter: EOF
        block: |        
          gem 'sufia', '{{sufia_version}}'
          gem 'flipflop', git: 'https://github.com/jcoyne/flipflop.git', branch: 'hydra'
          gem 'hydra-role-management', '{{hydra_role_management_version}}'
          gem 'curation_concerns', '{{curation_concerns_version}}'
          gem 'figaro', '{{figaro_version}}'
    - name: Install gems
      # CHECK
      shell: "{{sources}} bundle install"
      args:
        executable: /bin/bash
        chdir: ~/workspace/{{app_name}}
    - name: Install Bootstrap 3
      shell: "{{sources}} rails generate jquery:datatables:install bootstrap3"
      args:
        executable: /bin/bash
        chdir: ~/workspace/{{app_name}}    
    - name: Generate Sufia files
      shell: "{{sources}} rails generate sufia:install -f"
      args:
        executable: /bin/bash
        chdir: ~/workspace/{{app_name}}
    - name: Give Sufia migrations time delay
      shell: sleep 2 
    - name: Generate Sufia work
      shell: "{{sources}} rails generate sufia:work Work"
      args:
        executable: /bin/bash
        chdir: ~/workspace/{{app_name}}
    - name: Give Work migrations time delay
      shell: sleep 2 
    - name: Generate roles
      shell: "{{sources}} rails generate roles"
      args:
        executable: /bin/bash
        chdir: ~/workspace/{{app_name}}
    - name: Give Role migrations time delay
      shell: sleep 2 
    - name: Generate figaro files
      shell: "{{sources}} bundle exec figaro install"
      args:
        executable: /bin/bash
        chdir: ~/workspace/{{app_name}}
    - name: Perform migration
      # CHECK
      shell: "{{sources}} rails db:migrate"
      args:
        executable: /bin/bash
        chdir: ~/workspace/{{app_name}}
    - name: Create normal user
      shell: "{{sources}} rails runner 'User.create!({email: \"user@ualberta.ca\", password:\"user123\", password_confirmation:\"user123\"})'"
      args:
        executable: /bin/bash
        chdir: ~/workspace/{{app_name}}
    - name: Create admin user
      shell: "{{sources}} rails runner 'admin_user = User.create!({email: \"admin@ualberta.ca\", password:\"admin123\", password_confirmation:\"admin123\"}); admin_role = Role.create(name: \"admin\"); admin_role.users << admin_user; admin_role.save'"
      args:
        executable: /bin/bash
        chdir: ~/workspace/{{app_name}}
    - name: Install fits.sh
      become: yes      
      unarchive:
        src: http://projects.iq.harvard.edu/files/fits/files/fits-0.8.5.zip
        dest: /opt/
        remote_src: yes
        copy: no
    - name: Make fits.sh executable
      become: yes
      file:         
        path: /opt/fits-0.8.5/
        mode: 0777
        recurse: yes
    - name: Add fits.sh path to rails application
      lineinfile: 
        dest: ~/workspace/{{app_name}}/config/initializers/sufia.rb 
        regexp: '# config.fits_path = "fits.sh"' 
        line: 'config.fits_path = "/opt/fits-0.8.5/fits.sh"'
    - name: Bind Rails application to all ports
      blockinfile:
        dest: ~/workspace/{{app_name}}/config/boot.rb
        insertafter: EOF
        block: |        
          require 'rails/commands/server'
          module Rails
            class Server
              def default_options
                super.merge(Host: '0.0.0.0', Port: 3000)
              end
            end
          end
    - name: Copy Sufia gem for easy lookup
      copy: src=~/.rvm/gems/ruby-{{ruby_version}}@{{gemset}}/gems/sufia-{{sufia_version}} dest=~/workspace/sufia-{{sufia_version}}

# End of clean application
...
